puphpet.nginx.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:Nginx:index }

puphpet.nginx.upstream:
    pattern:  /upstream
    defaults: { _controller: PuphpetMainBundle:Nginx:upstream }

puphpet.nginx.proxy:
    pattern:  /proxy
    defaults: { _controller: PuphpetMainBundle:Nginx:proxy }

puphpet.nginx.vhost:
    pattern:  /vhost
    defaults: { _controller: PuphpetMainBundle:Nginx:vhost }

puphpet.nginx.vhost_rewrite:
    pattern:  /vhost-rewrite/{vhostId}
    defaults: { _controller: PuphpetMainBundle:Nginx:vhostRewrite }

puphpet.nginx.location:
    pattern:  /location/{vhostId}
    defaults: { _controller: PuphpetMainBundle:Nginx:location }

puphpet.nginx.location_rewrite:
    pattern:  /location-rewrite/{vhostId}/{locationId}
    defaults: { _controller: PuphpetMainBundle:Nginx:locationRewrite }
